### ISSUE TITLE
Angular HTML control flow formatting breaks with #{

### ISSUE THREAD

**Issue by jkaartoluoma** [NesTeRDGIT/js-beautify-extentions#1]
"Item #{{ office }}" breaks the formatting
![kuva](https://github.com/NesTeRDGIT/js-beautify-extentions/assets/32455688/5ac12572-13ef-4e77-8041-d63a8a30cd38)

With space it works "Item # {{ office }}"
![kuva](https://github.com/NesTeRDGIT/js-beautify-extentions/assets/32455688/c5ba7008-f9ac-42f4-a28c-142c28878cc5)

**Comment by wwoly** [comment]
I noticed the same issue just now!

**Comment by NesTeRDGIT** [comment]
This extension only enables js-beautify for VSCode. The js-beautify library formats the text.
Report this bug to the js-beautify repository
https://github.com/beautifier/js-beautify/issues
