### ISSUE TITLE
Example - How to make it works for Support for Angular control flow formatting

### ISSUE THREAD

**Issue by vitoexe** [NesTeRDGIT/js-beautify-extentions#2]
For those who struggle to understand the documentation:

Create a file ".jsbeautifyrc.json" in the main project directory, with the content:
{ "html": { "templating": [ "angular" ], "format": { "indentHandlebars": true } } }

**Comment by NesTeRDGIT** [comment]
Answer: https://github.com/NesTeRDGIT/js-beautify-extentions/issues/3
The file is not required. This is options
