### ISSUE TITLE
After activating Angulat templating, the size of the indents increases

### ISSUE THREAD

**Issue by vitoexe** [NesTeRDGIT/js-beautify-extentions#3]
After activating Angulat templating, the size of the indents increases (they are not like the default ones from the editor)

I don't fully understand parameter mapping myself. How to change the size of indents? Or leave it unoverwritten (default from editor)

**Comment by NesTeRDGIT** [comment]
The file is not required
You can find the parameters by searching in VSCode
For example
[indent_size]: [editor.tabSize];
 
[indent_size] -parameter js-beautify
[editor.tabSize] - VSCode parameter

![Безымянный](https://github.com/NesTeRDGIT/js-beautify-extentions/assets/82501591/30f43197-5a14-481f-ac8a-6ab581cf0991)

**Comment by NesTeRDGIT** [comment]
Probably by default VSСode divides editor.tabSize by 2... I'll see how VSСode does this.
Defaul value editor.tabSize=4.

**Comment by NesTeRDGIT** [comment]
I didn't think about it...
I'll fix this
https://code.visualstudio.com/docs/editor/codebasics#_autodetection

**Comment by NesTeRDGIT** [comment]
fixed 1.0.2

**Comment by vitoexe** [comment]
THX <3
