### ISSUE TITLE
"templating: angular" works only if set in .jsbeautifyrc.json ?

### ISSUE THREAD

**Issue by vitoexe** [NesTeRDGIT/js-beautify-extentions#4]
Im not sure where is problem.
It looks like options in VSC setting file not working ("js-beautify-for-vscode.html.templating": ["angular"])? 
Templating is always same like AUTO

But if I change it in .jsbeautifyrc.json the Templating (indentation) is much nicer and looks like Angular Documentation 
`{"html": { "templating": ["angular"] } }`

![image](https://github.com/NesTeRDGIT/js-beautify-extentions/assets/5330373/5d41e65f-2431-447c-ab0e-5217e31dfde9)

Video Example: 

https://github.com/NesTeRDGIT/js-beautify-extentions/assets/5330373/522b0f20-410e-4cc7-a7f3-f061929e2856

**Comment by NesTeRDGIT** [comment]
If you are using a file and do not specify indentation parameters, js-beautify will set the parameters. Probably = 4.
If you do not use the file, VSCode will set the parameters. Using autodetection or default value(tabSize), it is visible in the status bar
templating - does not affect the Tab size
If you want to use the file. Then specify indent_size in the file
![Безымянный](https://github.com/NesTeRDGIT/js-beautify-extentions/assets/82501591/5653b263-3b46-4833-b306-6f392d21f702)

**Comment by NesTeRDGIT** [comment]
Always, unless you specify indentation options. vscode will install them on its own

**Comment by vitoexe** [comment]
I changed the title because it was misleading.

**Comment by vitoexe** [comment]
If you set "template: angular" in the .js file beautify.json, then it looks like in the Angular documentation (additional indents under @FOR)

If you set it in VSC configuration it looks like "template: auto"

**Watch the video carefully**

https://github.com/NesTeRDGIT/js-beautify-extentions/assets/5330373/522b0f20-410e-4cc7-a7f3-f061929e2856

**Comment by NesTeRDGIT** [comment]
I'll check this later.

ps having a configuration file in the project root, even if it is empty, causes vcs parameters to be ignored

**Comment by vitoexe** [comment]
> I'll check this later.
> 
> ps having a configuration file in the project root, even if it is empty, causes vcs parameters to be ignored

CONFIRMED: Problem exist because of empty .jsbeautifyrc.json file
