### ISSUE TITLE
How to preserve-inline imports?   "brace_style": "preserve-inline"  not working.

### ISSUE THREAD

**Issue by vitoexe** [NesTeRDGIT/js-beautify-extentions#5]
How to preserve-inline imports?  

<img width="1309" alt="image" src="https://github.com/NesTeRDGIT/js-beautify-extentions/assets/5330373/aeacf627-b60f-48b4-afd9-0de2f2e66b52">

I create .jsbeautifyrc.json to add "brace_style": "preserve-inline", but it doesn't work, imports looks always like this:

<img width="1339" alt="image" src="https://github.com/NesTeRDGIT/js-beautify-extentions/assets/5330373/7a988355-c7d7-47f4-88ba-7bdcac496b82">

My .jsbeautifyrc.json file
```
{
  "html": {
    "templating": [
      "angular"
    ],
    "format": {
      "indentHandlebars": true
    }
  },
  "brace_style": [
    "preserve-inline"
  ]
}
```

**Comment by NesTeRDGIT** [comment]
1) Your file should be:
```
{
  "html": {
    "templating": [
      "angular"
    ],
   "indentHandlebars": true
  }, 
  "js": {
     "brace_style": [
        "preserve-inline"
      ]
  }
}
```
2) File format (https://github.com/NesTeRDGIT/js-beautify-extentions/blob/main/README.md):
```
{
    html: HTMLBeautifyOptions,
    css: CSSBeautifyOptions,
    js: JSBeautifyOptions
}
```
HTMLBeautifyOptions/CSSBeautifyOptions/JSBeautifyOptions are [js-beautify](https://github.com/beautifier/js-beautify) settings
3) You change the HTML settings, but format the TS file
4) This extension only connects js-beautify to VSCode, but formats the text - js-beautify
https://github.com/beautifier/js-beautify
https://beautifier.io/
5) If you think js-beautify is not working correctly, please let them know (https://github.com/beautifier/js-beautify)
6) I think this will solve your problem(checked https://beautifier.io/)
```
"brace_style": [
    "preserve-inline"
  ]
```
